#ifndef P2P_TECHDEMO_RUDPEVENTTYPE_H
#define P2P_TECHDEMO_RUDPEVENTTYPE_H

enum class RUdpEventType : int
{
    NONE,
    CONNECT,
    DISCONNECT,
    RECEIVE
};

#endif // P2P_TECHDEMO_RUDPEVENTTYPE_H
