---
version: "3"
services:
  e2e_test:
    build:
      context: "."
      dockerfile: './test/Dockerfile'
    container_name: "p2p-techdemo-e2e-test"
    image: "p2p-techdemo-e2e-test"
    stdin_open: true
    tty: true
    volumes:
      - "./app:/var/app/app"
      - "./cmake:/var/app/cmake"
      - "./core:/var/app/core"
      - "./lib:/var/app/lib"
      - "./module:/var/app/module"
      - "./test:/var/app/test"
      - "./CMakeLists.txt:/var/app/CMakeLists.txt"
    # ビルドしてからテストを実行する
    command: >
      cd /var/app/build &&
      /usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -G "CodeBlocks - Unix Makefiles" /var/app &&
      /usr/bin/cmake --build /var/app/build --target all -- -j 4
    #  && /var/app/cmake-build-test/test/e2e/rudp/basic_connection -r console -d yes --order lex