version: "3.7"
services:
  dev_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-dev-server
    stdin_open: true
    tty: true
    container_name: p2p-techdemo-dev-server
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2222:22"
      - "7777:7777"
    command: >
      bash -c "chmod -R 777 $APPROOT/cmake-build-debug-remote
              && /usr/sbin/sshd -D"
    volumes:
      - ./.git:${DC_APP_ROOT}/.git
      - cmake_build_debug_remote:${DC_APP_ROOT}/cmake-build-debug-remote
      - conan:/root/.conan
  test_base: &test_base
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-test-base
    stdin_open: true
    tty: true
    volumes:
      - ./.git:${DC_APP_ROOT}/.git
      - ./app:${DC_APP_ROOT}/app
      - ./cmake:${DC_APP_ROOT}/cmake
      - ./docker:${DC_APP_ROOT}/docker
      - ./lib:${DC_APP_ROOT}/lib
      - ./module:${DC_APP_ROOT}/module
      - ./test:${DC_APP_ROOT}/test
      - ./CMakeLists.txt:${DC_APP_ROOT}/CMakeLists.txt
      - ./conanfile.txt:${DC_APP_ROOT}/conanfile.txt
      - cmake_build_test:${DC_APP_ROOT}/cmake-build-test
      - conan:/root/.conan
  feature_test:
    <<: *test_base
    container_name: p2p-techdemo-feature-test
    command: >
      bash -c "/bin/bash ./docker/script/build.sh &&
               /bin/bash ./docker/script/run_feature_test.sh"
  unit_test:
    <<: *test_base
    container_name: p2p-techdemo-unit-test
    command: >
      bash -c "/bin/bash ./docker/script/build.sh &&
               /bin/bash ./docker/script/run_unit_test.sh"
volumes:
  cmake_build_debug_remote:
    driver: local
  cmake_build_test:
    driver: local
  conan:
    driver: local
