---
version: "3"
services:
  test_template: &test_template
    build:
      context: "."
      dockerfile: "./test/Dockerfile"
    container_name: "p2p-techdemo-test"
    image: "p2p-techdemo-test"
    stdin_open: true
    tty: true
    volumes:
      - "./app:/var/app/app"
      - "./cmake:/var/app/cmake"
      - "./core:/var/app/core"
      - "./lib:/var/app/lib"
      - "./module:/var/app/module"
      - "./test:/var/app/test"
      - "./CMakeLists.txt:/var/app/CMakeLists.txt"
      - "build:/var/app/build"
  e2e_test:
    <<: *test_template
    command: /bin/bash /var/app/test/run_e2e_test.sh
  unit_test:
    <<: *test_template
    command: /bin/bash /var/app/test/run_unit_test.sh
volumes:
 build:
   driver: 'local'
