---
version: "3"
services:
  e2e_test:
    build:
      context: "."
      dockerfile: './test/Dockerfile'
    container_name: "p2p-techdemo-e2e-test"
    image: "p2p-techdemo-e2e-test"
    stdin_open: true
    tty: true
    volumes:
      - "./app:/var/app/app"
      - "./cmake:/var/app/cmake"
      - "./core:/var/app/core"
      - "./lib:/var/app/lib"
      - "./module:/var/app/module"
      - "./test:/var/app/test"
      - "./CMakeLists.txt:/var/app/CMakeLists.txt"
      - "build:/var/app/build"
    command: /bin/bash /var/app/test/run.sh
volumes:
 build:
   driver: 'local'