version: "3.7"
services:
  dev_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-dev-server
    stdin_open: true
    tty: true
    container_name: p2p-techdemo-dev-server
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2222:22"
      - "7777:7777"
    command: >
      bash -c "chmod -R 777 /var/app/cmake-build-debug-remote &&
               /usr/sbin/sshd -D"
    volumes:
      - ./.git:/var/app/.git
      - cmake_build_debug_remote:/var/app/cmake-build-debug-remote
      - conan:/root/.conan
  test_base: &test_base
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-test-base
    stdin_open: true
    tty: true
    volumes:
      - ./.git:/var/app/.git
      - ./app:/var/app/app
      - ./cmake:/var/app/cmake
      - ./docker:/var/app/docker
      - ./lib:/var/app/lib
      - ./module:/var/app/module
      - ./test:/var/app/test
      - ./CMakeLists.txt:/var/app/CMakeLists.txt
      - ./conanfile.txt:/var/app/conanfile.txt
      - conan:/root/.conan
  all_tests:
    <<: *test_base
    container_name: p2p-techdemo-all-test
    volumes:
      - cmake_build_test:/var/app/cmake-build-test
    command: >
      bash -c "/bin/bash ./docker/script/build/build_all.bash &&
               /bin/bash ./docker/script/test/run_all_tests.bash"
  all_tests_with_asan:
    <<: *test_base
    container_name: p2p-techdemo-all-test
    volumes:
      - cmake_build_test_asan:/var/app/cmake-build-test
    command: >
      bash -c "/bin/bash ./docker/script/build/build_all_with_asan.bash &&
               /bin/bash ./docker/script/test/run_all_tests.bash"
  all_tests_with_lsan:
    <<: *test_base
    container_name: p2p-techdemo-all-test
    volumes:
      - cmake_build_test_lsan:/var/app/cmake-build-test
    command: >
      bash -c "/bin/bash ./docker/script/build/build_all_with_lsan.bash &&
               /bin/bash ./docker/script/test/run_all_tests.bash"
  all_tests_with_msan:
    <<: *test_base
    container_name: p2p-techdemo-all-test
    volumes:
      - cmake_build_test_msan:/var/app/cmake-build-test
    command: >
      bash -c "/bin/bash ./docker/script/build/build_all_with_msan.bash &&
               /bin/bash ./docker/script/test/run_all_tests.bash"
  all_tests_with_tsan:
    <<: *test_base
    container_name: p2p-techdemo-all-test
    volumes:
      - cmake_build_test_tsan:/var/app/cmake-build-test
    command: >
      bash -c "/bin/bash ./docker/script/build/build_all_with_tsan.bash &&
               /bin/bash ./docker/script/test/run_all_tests.bash"
volumes:
  cmake_build_debug_remote:
    driver: local
  cmake_build_test:
    driver: local
  cmake_build_test_asan:
    driver: local
  cmake_build_test_lsan:
    driver: local
  cmake_build_test_msan:
    driver: local
  cmake_build_test_tsan:
    driver: local
  conan:
    driver: local
