version: "3.7"
services:
  dev_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-dev-server
    stdin_open: true
    tty: true
    container_name: p2p-techdemo-dev-server
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2222:22"
      - "7777:7777"
    command: >
      bash -c "chmod -R 777 /var/app/cmake-build-debug-remote &&
               /usr/sbin/sshd -D"
    volumes:
      - ./.git:/var/app/.git
      - cmake_build_debug_remote:/var/app/cmake-build-debug-remote
      - conan:/root/.conan
  test_base: &test_base
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-test-base
    stdin_open: true
    tty: true
    volumes:
      - ./.git:/var/app/.git
      - ./app:/var/app/app
      - ./cmake:/var/app/cmake
      - ./docker:/var/app/docker
      - ./lib:/var/app/lib
      - ./module:/var/app/module
      - ./test:/var/app/test
      - ./CMakeLists.txt:/var/app/CMakeLists.txt
      - ./conanfile.txt:/var/app/conanfile.txt
      - cmake_build_test:/var/app/cmake-build-test
      - conan:/root/.conan
  all_test:
    <<: *test_base
    container_name: p2p-techdemo-all-test
    command: >
      bash -c "/bin/bash ./docker/script/build.sh &&
               /bin/bash ./docker/script/run_all_test.sh"
volumes:
  cmake_build_debug_remote:
    driver: local
  cmake_build_test:
    driver: local
  conan:
    driver: local
