version: "3.7"
services:
  base: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-base
    stdin_open: true
    tty: true
    volumes:
      - conan:/root/.conan
  dev_server:
    <<: *base
    container_name: p2p-techdemo-dev-server
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2222:22"
      - "7777:7777"
  e2e_test:
    <<: *base
    container_name: p2p-techdemo-e2e-test
    command: >
      bash -c "/bin/bash ./docker/script/build.sh &&
               /bin/bash ./docker/script/run_e2e_test.sh"
  unit_test:
    <<: *base
    container_name: p2p-techdemo-unit-test
    command: >
      bash -c "/bin/bash ./docker/script/build.sh &&
               /bin/bash ./docker/script/run_unit_test.sh"
volumes:
  conan:
    driver: local
