version: "3.7"
services:
  dev_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: p2p-techdemo-dev-server
    stdin_open: true
    tty: true
    container_name: p2p-techdemo-dev-server
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2222:22"
      - "7777:7777"
    environment:
      - CMAKE_BUILD_TYPE=Debug
    command: >
      bash -c "chmod -R 777 /var/app/cmake-build-debug-remote &&
               /usr/sbin/sshd -D"
    volumes:
      - ./.git:/var/app/.git
      - cmake_build_debug_remote:/var/app/cmake-build-debug-remote
      - conan:/root/.conan

volumes:
  cmake_build_debug_remote:
    driver: local
  conan:
    driver: local
