version: 2
jobs:
  build:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /root
    steps:
      - restore_cache:
          keys:
            - build-{{ .Branch }}
      - checkout
      - run:
          name: "Create Build Directory"
          command: |
            if [[ ! -e ./build ]]; then
              mkdir ./build
            fi
      - run:
          name: "Build"
          command: /bin/bash ./test/build.sh
      - save_cache:
          key: build-{{ .Branch }}
          paths:
            - .hunter
            - build
      - persist_to_workspace:
          root: .
          paths:
            - .hunter
            - build
  test:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /root
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Enable XML Reporter"
          command: echo "export CATCH_REPORTER=xml" >> $BASH_ENV
      - run:
          name: "Run E2E Test"
          command: /bin/bash ./test/run_e2e_test.sh
      - run:
          name: "Run Unit Test"
          command: /bin/bash ./test/run_unit_test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build