version: 2
jobs:
  build:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /var/app
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}
      - run:
          name: "Create Build Directory"
          command: |
            if [[ ! -e ./cmake-build-test ]]; then
              mkdir ./cmake-build-test
            fi
      - run:
          name: "Build"
          command: /bin/bash ./docker/scripts/build.sh
      - save_cache:
          key: build-{{ .Branch }}-{{ checksum "./cmake-build-test/CMakeCache.txt" }}
          paths:
            - /root/.hunter
            - /var/app/cmake-build-test
  test:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /var/app
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}
      - run:
          name: "Create Test Results Directory"
          command: |
            if [[ ! -e ./test-results ]]; then
              mkdir ./test-results
            fi
      - run:
          name: "Enable JUnit Reporter"
          command: echo "export CATCH_REPORTER=junit" >> $BASH_ENV
      - run:
          name: "Run E2E Test"
          command: /bin/bash ./docker/scripts/run_e2e_test.sh
      - run:
          name: "Run Unit Test"
          command: /bin/bash ./docker/scripts/run_unit_test.sh
      - store_test_results:
          path: /var/app/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build