version: 2
jobs:
  build:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /tmp/build
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}-
      - run:
          name: "Create Build Directory"
          command: |
            if [[ ! -e ./cmake-build-test ]]; then
              mkdir ./cmake-build-test
            fi
      - run:
          name: "Build"
          command: /bin/bash ./test/build.sh
      - save_cache:
          key: build-{{ .Branch }}-{{ checksum "./cmake-build-test/CMakeCache.txt" }}
          paths:
            - /root/.hunter
            - /tmp/build/cmake-build-test
  test:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /tmp/test
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}
      - run:
          name: "Create Test Results Directory"
          command: |
            if [[ ! -e /tmp/test-results ]]; then
              mkdir /tmp/test-results
            fi
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: "Enable XML Reporter"
          command: echo "export CATCH_REPORTER=xml" >> $BASH_ENV
      - run:
          name: "Run E2E Test"
          command: /bin/bash ./test/run_e2e_test.sh
      - run:
          name: "Run Unit Test"
          command: /bin/bash ./test/run_unit_test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build