version: 2
jobs:
  build:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /var/app
    store_test_results:
      path: /tmp/test-results
    steps:
      - checkout
      - run:
          name: "Create Build Directory"
          command: |
            if [[ ! -e ./build ]]; then
              mkdir ./build
            fi
      - run:
          name: "Run E2E Test"
          command: /bin/bash ./test/run_e2e_test.sh
      - run:
          name: "Run Unit Test"
          command: /bin/bash ./test/run_unit_test.sh
      - persist_to_workspace:
          root: .
          paths:
            - .git
            - .hunter
            - build