version: 2
jobs:
  build:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /var/app
    steps:
      - checkout
      - run:
          name: "Create Build Directory"
          command: |
            if [[ ! -e ./build ]]; then
              mkdir ./build
            fi
      - run:
          name: "Build Project"
          command: /bin/bash ./test/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - .hunter
            - build
  test:
    docker:
      - image: 42milez/alpine-cmake-clang:latest
    working_directory: /var/app
    store_test_results:
      path: /tmp/test-results
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Run E2E Test"
          command: /bin/bash ./test/run_e2e_test.sh
      - run:
          name: "Run Unit Test"
          command: /bin/bash ./test/run_unit_test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build