#ifndef P2P_TECHDEMO_CORE_BASE_ERRORS_H
#define P2P_TECHDEMO_CORE_BASE_ERRORS_H

enum class Error : int {
    ERR_ALREADY_IN_USE,
    ERR_INVALID_PARAMETER,
    ERR_UNAVAILABLE,
    ERR_UNCONFIGURED,
    ERROR,
    FAILED,
    OK
};

#endif // P2P_TECHDEMO_CORE_BASE_ERRORS_H
