#ifndef P2P_TECHDEMO_TEST_FEATURE_VAR_H_
#define P2P_TECHDEMO_TEST_FEATURE_VAR_H_

namespace test
{
    const uint16_t HOST_PORT   = 49152;
    const uint16_t GUEST1_PORT = 49153;
    const uint16_t GUEST2_PORT = 49154;

    const uint32_t DEFAULT_TIMEOUT = 5000; // msec

    const std::string LARGE_PAYLOAD_1 =
        "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be"
        "For my unconquerable soul. In the fell clutch of circumstance I have not winced nor cried aloud."
        "Under the bludgeonings of chance My head is bloody, but unbowed. Beyond this place of wrath and tears"
        "Looms but the Horror of the shade, And yet the menace of the years Finds and shall find me unafraid."
        "It matters not how strait the gate, How charged with punishments the scroll, I am the master of my fate,"
        "I am the captain of my soul."
        "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be"
        "For my unconquerable soul. In the fell clutch of circumstance I have not winced nor cried aloud."
        "Under the bludgeonings of chance My head is bloody, but unbowed. Beyond this place of wrath and tears"
        "Looms but the Horror of the shade, And yet the menace of the years Finds and shall find me unafraid."
        "It matters not how strait the gate, How charged with punishments the scroll, I am the master of my fate,"
        "I am the captain of my soul."
        "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be"
        "For my unconquerable soul. In the fell clutch of circumstance I have not winced nor cried aloud."
        "Under the bludgeonings of chance My head is bloody, but unbowed. Beyond this place of wrath and tears"
        "Looms but the Horror of the shade, And yet the menace of the years Finds and shall find me unafraid."
        "It matters not how strait the gate, How charged with punishments the scroll, I am the master of my fate,"
        "I am the captain of my soul."
        "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be"
        "For my unconquerable soul. In the fell clutch of circumstance I have not winced nor cried aloud."
        "Under the bludgeonings of chance My head is bloody, but unbowed. Beyond this place of wrath and tears"
        "Looms but the Horror of the shade, And yet the menace of the years Finds and shall find me unafraid."
        "It matters not how strait the gate, How charged with punishments the scroll, I am the master of my fate,"
        "I am the captain of my soul."
        "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be"
        "For my unconquerable soul. In the fell clutch of circumstance I have not winced nor cried aloud."
        "Under the bludgeonings of chance My head is bloody, but unbowed. Beyond this place of wrath and tears"
        "Looms but the Horror of the shade, And yet the menace of the years Finds and shall find me unafraid."
        "It matters not how strait the gate, How charged with punishments the scroll, I am the master of my fate,"
        "I am the captain of my soul."
        "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be"
        "For my unconquerable soul. In the fell clutch of circumstance I have not winced nor cried aloud."
        "Under the bludgeonings of chance My head is bloody, but unbowed. Beyond this place of wrath and tears"
        "Looms but the Horror of the shade, And yet the menace of the years Finds and shall find me unafraid."
        "It matters not how strait the gate, How charged with punishments the scroll, I am the master of my fate,"
        "I am the captain of my soul."
        "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be"
        "For my unconquerable soul. In the fell clutch of circumstance I have not winced nor cried aloud."
        "Under the bludgeonings of chance My head is bloody, but unbowed. Beyond this place of wrath and tears"
        "Looms but the Horror of the shade, And yet the menace of the years Finds and shall find me unafraid."
        "It matters not how strait the gate, How charged with punishments the scroll, I am the master of my fate,"
        "I am the captain of my soul.";

    const std::string LARGE_PAYLOAD_2 =
        ".luos ym fo niatpac eht ma I ,etaf ym fo retsam eht ma I ,llorcs eht stnemhsinup htiw degrahc woH"
        ",etag eht tiarts woh ton srettam tI .diarfanu em dnif llahs dna sdniF sraey eht fo ecanem eht tey dnA"
        ",edahs eht fo rorroH eht tub smooL sraet dna htarw fo ecalp siht dnoyeB .dewobnu tub ,ydoolb si daeh yM"
        "ecnahc fo sgninoegdulb eht rednU .duola deirc ron decniw ton evah I ecnatsmucric fo hctulc llef eht nI"
        ".luos elbareuqnocnu ym roF eb yam sdog revetahw knaht I ,elop ot elop morf tip eht sa kcalB ,em srevoc"
        "taht thgin eht fo tuO"
        ".luos ym fo niatpac eht ma I ,etaf ym fo retsam eht ma I ,llorcs eht stnemhsinup htiw degrahc woH"
        ",etag eht tiarts woh ton srettam tI .diarfanu em dnif llahs dna sdniF sraey eht fo ecanem eht tey dnA"
        ",edahs eht fo rorroH eht tub smooL sraet dna htarw fo ecalp siht dnoyeB .dewobnu tub ,ydoolb si daeh yM"
        "ecnahc fo sgninoegdulb eht rednU .duola deirc ron decniw ton evah I ecnatsmucric fo hctulc llef eht nI"
        ".luos elbareuqnocnu ym roF eb yam sdog revetahw knaht I ,elop ot elop morf tip eht sa kcalB ,em srevoc"
        "taht thgin eht fo tuO"
        ".luos ym fo niatpac eht ma I ,etaf ym fo retsam eht ma I ,llorcs eht stnemhsinup htiw degrahc woH"
        ",etag eht tiarts woh ton srettam tI .diarfanu em dnif llahs dna sdniF sraey eht fo ecanem eht tey dnA"
        ",edahs eht fo rorroH eht tub smooL sraet dna htarw fo ecalp siht dnoyeB .dewobnu tub ,ydoolb si daeh yM"
        "ecnahc fo sgninoegdulb eht rednU .duola deirc ron decniw ton evah I ecnatsmucric fo hctulc llef eht nI"
        ".luos elbareuqnocnu ym roF eb yam sdog revetahw knaht I ,elop ot elop morf tip eht sa kcalB ,em srevoc"
        "taht thgin eht fo tuO"
        ".luos ym fo niatpac eht ma I ,etaf ym fo retsam eht ma I ,llorcs eht stnemhsinup htiw degrahc woH"
        ",etag eht tiarts woh ton srettam tI .diarfanu em dnif llahs dna sdniF sraey eht fo ecanem eht tey dnA"
        ",edahs eht fo rorroH eht tub smooL sraet dna htarw fo ecalp siht dnoyeB .dewobnu tub ,ydoolb si daeh yM"
        "ecnahc fo sgninoegdulb eht rednU .duola deirc ron decniw ton evah I ecnatsmucric fo hctulc llef eht nI"
        ".luos elbareuqnocnu ym roF eb yam sdog revetahw knaht I ,elop ot elop morf tip eht sa kcalB ,em srevoc"
        "taht thgin eht fo tuO"
        ".luos ym fo niatpac eht ma I ,etaf ym fo retsam eht ma I ,llorcs eht stnemhsinup htiw degrahc woH"
        ",etag eht tiarts woh ton srettam tI .diarfanu em dnif llahs dna sdniF sraey eht fo ecanem eht tey dnA"
        ",edahs eht fo rorroH eht tub smooL sraet dna htarw fo ecalp siht dnoyeB .dewobnu tub ,ydoolb si daeh yM"
        "ecnahc fo sgninoegdulb eht rednU .duola deirc ron decniw ton evah I ecnatsmucric fo hctulc llef eht nI"
        ".luos elbareuqnocnu ym roF eb yam sdog revetahw knaht I ,elop ot elop morf tip eht sa kcalB ,em srevoc"
        "taht thgin eht fo tuO"
        ".luos ym fo niatpac eht ma I ,etaf ym fo retsam eht ma I ,llorcs eht stnemhsinup htiw degrahc woH"
        ",etag eht tiarts woh ton srettam tI .diarfanu em dnif llahs dna sdniF sraey eht fo ecanem eht tey dnA"
        ",edahs eht fo rorroH eht tub smooL sraet dna htarw fo ecalp siht dnoyeB .dewobnu tub ,ydoolb si daeh yM"
        "ecnahc fo sgninoegdulb eht rednU .duola deirc ron decniw ton evah I ecnatsmucric fo hctulc llef eht nI"
        ".luos elbareuqnocnu ym roF eb yam sdog revetahw knaht I ,elop ot elop morf tip eht sa kcalB ,em srevoc"
        "taht thgin eht fo tuO"
        ".luos ym fo niatpac eht ma I ,etaf ym fo retsam eht ma I ,llorcs eht stnemhsinup htiw degrahc woH"
        ",etag eht tiarts woh ton srettam tI .diarfanu em dnif llahs dna sdniF sraey eht fo ecanem eht tey dnA"
        ",edahs eht fo rorroH eht tub smooL sraet dna htarw fo ecalp siht dnoyeB .dewobnu tub ,ydoolb si daeh yM"
        "ecnahc fo sgninoegdulb eht rednU .duola deirc ron decniw ton evah I ecnatsmucric fo hctulc llef eht nI"
        ".luos elbareuqnocnu ym roF eb yam sdog revetahw knaht I ,elop ot elop morf tip eht sa kcalB ,em srevoc"
        "taht thgin eht fo tuO";
} // namespace test

#endif // P2P_TECHDEMO_TEST_FEATURE_VAR_H_
